### ISSUE TITLE
Clarify correct convention for latlon vs lonlat?

### ISSUE THREAD

**Issue by kingkong-cmd** [dakk/libweatherrouting#13]
It seems the convention for order of latitude vs longitude is to use (lat, lon). In the docs for the definition of trackpoints you say:

`Define a list of trackpoints as lat,long tuples (almost 2) that have to be reached by the route
`

But the trackpoints shown adjacent to this seems to be (lon, lat) as this track is somewhere in the Med if (lon, lat), but in the middle of Africa if (lat, lon).

`track = ((5.1, 38.1), (5.2, 38.4), (5.7, 38.2))
`

**Comment by dakk** [comment]
I confirm you that lat_lon is the correct order; I updated the readme.
