### ISSUE TITLE
Customize steps interval

### ISSUE THREAD

**Issue by rgrente** [dakk/libweatherrouting#14]
Hello, 

Thanks for your great job.

I would like to do something, but i don’t know if it is allowed. I am using the LinearBestIsoRouter and i want to customize the steps interval.
Currently, the default interval between steps is 1 hour. That's what I understand and get it in the result.

I want to customize this interval, to get steps each 5 minutes by example. I am trying to do some customization, without success.

Could you help me ?
Thx

**Comment by ludohenin** [comment]
@rgrente I made this PR #15  as I wanted this feature as well.

**Comment by rgrente** [comment]
cool, seems to work fine. i will do some more testing. thx

**Comment by dakk** [comment]
Thanks for the contribution @ludohenin , I have time to take a look on your PR and other issues next week, a new library release will be available. @rgrente if you do some more testing on ludo PR, let us know so I can speed up my revision phase.

In the meanwhile, can I ask you how are you using the library? It could be cool to have a "Projects using this library" section in the readme

**Comment by ludohenin** [comment]
@dakk I'm using for player, trying to make my own router for virtual regatta. Not guaranteed something will come out of it more than running on my PC but who knows :)

**Comment by rgrente** [comment]
Exactly the same for me ! :)
Just run 2 routings now, one with QtVLM, and the other with the lib, same grib and polars, but the result is much more linear with the lib.
Not enough time at the moment to investigate !

**Comment by ludohenin** [comment]
@rgrente do you interpolate your grib data? that may explain some linearity.
Another one is that isochrones are fixed at 178 points per steps (from what I've seen so far)
I'm not yet to plotting the route so can't really say.

**Comment by dakk** [comment]
> @dakk I'm using as a playground, trying to make my own router for virtual regatta. Not guaranteed something will come out of it but who knows :)

That's cooler than expected :) I hope that libww will not bring you off course.

The pull request from @ludohenin solves the issue you proposed; for other question, please open a new issue
